server:
  port: 8082
  servlet:
    context-path: /
# 数据源配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.112.111:3306/sec_kill?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis
  redis:
    host: 192.168.112.111
    port: 6379
    database: 0
    password: 123456
    pool:
      max-active: 8
      max-idle: 8
      max-wait: 10000
      min-idle: 0
      timeout: 5000
  #rabbitMq
  rabbitmq:
    host: 192.168.112.111
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
        acknowledge-mode: manual  # 确认模式为手动确认-需要在代码中手动ACK
        retry:
          enabled: true           # 开启消费者出现异常情况下，进行重试消费，默认false
          max-attempts: 10         # 最大重试次数，默认为3
          initial-interval: 3000  # 重试间隔时间，默认1000(单位毫秒)